### ISSUE TITLE
Change "Cage" button label to "Level" and add window warning user to wait and remain stationary

### ISSUE THREAD

**Issue by westphae** [westphae/stratux#19]
'nuff said.  Maybe other options to "Level": Calibrate or Cal?  Reset?

**Comment by Nokomis449** [comment]
"Reset to Level" removes all doubt as to its purpose.  I also suggest a "Please wait..." window (or a plane icon tumbling on the screen) since the calibration takes more than a few seconds.

**Comment by westphae** [comment]
Thanks.  Good idea on the dialog box, I've had that thought myself; your comment confirms it.  I think I will have the "auto-level" done in the next release, so I'm thinking of changing the button to just "Reset AHRS".  That's what it really does--the leveling is (was) just one aspect of that.

**Comment by westphae** [comment]
Closed with ae92bae0d3af5c914c173ee9adb12dd04aba5c05.
